### ISSUE TITLE
Crash on notification settings

### ISSUE THREAD

**Issue by jfjallid** [SickGear/SickGear.Docker#6]
Whenever I try to access the notification settings the docker container crashes without any error messages. I'm running the container with your example command but with modified values for paths, uid and gid

**Comment by ressu** [comment]
Which platform are you running the image on? Crashing without any messages makes me think of a recent Docker bug that could be causing the crash.

**Comment by jfjallid** [comment]
I'm running it on CentOS x64.
Docker version 1.12.1, build 23cf638.

**Comment by jfjallid** [comment]
I've tried running it on Docker version 1.12.3, build 6b644ec and the problem remains.
When I run the developer image instead, the webserver crashes but the docker container keeps running. The webserver crashes with the message "The connection was reset" and no further output in the container log. I'm running the container interactively and after the webserver crashes it just hangs silently without writing anything else to stdout or stderr.

**Comment by ressu** [comment]
OK, I'll try and reproduce tonight.

**Comment by ressu** [comment]
I'm able to reproduce the issue. There doesn't appear to be any messages in the log or console. I'll try and dig deeper and try and find out what is causing the exit.

**Comment by jfjallid** [comment]
@ressu Any progress on this?

**Comment by ressu** [comment]
I'm having a hard time getting this resolved, it feels a lot like an musl compatibility issue. I'm currently trying to narrow down what is actually causing the crash and working backwards from there

**Comment by ressu** [comment]
The fixed builds should now be up. Took me a bit longer to get around to fixing this than I expected.. The only solution I could find was to switch away from the Alpine based image to Debian based image.

**Comment by jfjallid** [comment]
Yes, this solved the problem nicely. Thanks!

**Comment by deed02392** [comment]
@ressu this can be fixed by setting the threading stack size in SickGear. Thus we can continue to use Alpine as the base.

These are the refs to the root cause of the issue:

https://github.com/python-pillow/Pillow/issues/1935
https://github.com/python-pillow/Pillow/issues/1935#issuecomment-317198275
https://github.com/docker-library/python/issues/211#issuecomment-314919717
https://github.com/voidlinux/void-packages/issues/4147
https://github.com/voidlinux/void-packages/pull/6889/files

**Comment by ressu** [comment]
Cool, I personally prefer Alpine over Debian for the Docker image. Pull requests are welcome, I'm not sure when I'm able to revert PR #8 and test with the new threading stack sizes.

**Comment by deed02392** [comment]
So I've spoken with @JackDandy and we're working on testing a config directive for specifying the default thread stack size. That way we can revert to an Alpine based docker image in master, and just update the config template to specify the stack size to something large enough to keep it working. I haven't yet managed to test the PR over on kulta regarding this new config setting though.

**Comment by timm088** [comment]
Thanks for looking into the fix, however, shouldn't this one still be open ? Took me a little to dig it up is all

**Comment by deed02392** [comment]
@timm088 I basically investigated and resolved the issue entirely independently before realising it was fixed on master, because there wasn't an open issue :(
@ressu I do think you should make it clearer to people that this is a problem on dev with a change to the dev branches README. And look at my PR/harass @JackDandy for input :-)

**Comment by timm088** [comment]
Ok thanks. Would be great if that pr could be linked here, so I can just pulled it myself?

**Comment by deed02392** [comment]
Checkout the master branch

Or view my fork and the dev branch

**Comment by timm088** [comment]
Last commit on master was 

`9c3a158a5df3aea9f438e3038074282e2fbe5f44`
Confirmed my alpine docker container has this same commit in Sickgear / Settings / About

Problem still exists for Alpine docker images on current master branch

No problems if it isn't merged yet, I manually configured notifications via config.ini (which for me is mounted into the container each time)

**Comment by deed02392** [comment]
I can't find the commit you're referring to... This is the latest commit on the master branch: 

https://github.com/SickGear/SickGear.Docker/commit/16a847c08e2746f646f3c5460a2146c28a6312a3

**Comment by timm088** [comment]
Sorry, i'm referring to the master branch of Sickgear itself, not the dockerfile

i.e., you said its fixed on master? You mean changed to debian, not **actually** fixed (i.e, threading stack size fixed)

**Comment by deed02392** [comment]
If you just want to change the SickGear version to fix this issue, you can use this commit from the current hotfix branch: 70edd5462fca9ebdfc4ffa6caef7708219e79704

Then set the stack_size = 327680 under General in config.ini

**Comment by timm088** [comment]
Hotfix branch? 
There are only two visible branches...

**Comment by deed02392** [comment]
Did you actually find the commit I referred to?

**Comment by timm088** [comment]
You do realise there is no hotfix branch right? 
https://github.com/SickGear/SickGear/branches/all

Guessing hotfix branch is private?

You mean this commit? https://github.com/sickgear/sickgear/commit/70edd5462fca9ebdfc4ffa6caef7708219e79704

**Comment by deed02392** [comment]
https://git.kulta.us/SickGear/SickGear/src/hotfix/0.12.26

That's the right commit yes.

**Comment by timm088** [comment]
Merged into master on github now for anyone else that might come across this.
https://github.com/SickGear/SickGear/commit/2c2a5b175f5fec0ba39a7eeb776971474d157268
